### ISSUE TITLE
Bug report: td-sidenav-content is not resized properly

### ISSUE THREAD

**Issue by Enngage** [Teradata/covalent#726]
#### Bug Report

Hi guys,

The 'td-sidenav-content' used in 'Manage list Layout' is often not resized correctly. This issue can be reproduced also on the live  
[https://teradata.github.io/covalent-quickstart/users](https://teradata.github.io/covalent-quickstart/users) demo:

![sidenav](https://user-images.githubusercontent.com/7137351/27760867-0a220fb2-5e52-11e7-8a66-f3691c727670.gif)

This can be fixed in browser simply by reapplying the 'display:flex' of the 'mat-toolbar' class. It seems like the flex is not applying under some circumstances when navigating from one component to another. 

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Latest Chrome + Opera (haven't tried FF)

####  Did this work in previous versions of Angular / Material?

Yes, this actually worked before I upgraded to latest version of both Angular & Material.

Ps: Thank you for doing awesome job on this project!

**Comment by emoralesb05** [comment]
Huh, this is weird. It might be a problem with the animations in 4.2.0.. gonna start debugging and see whats happening.

Thanks for the report! 😄

**Comment by jotatoledo** [comment]
I think I reported this a couple of weeks ago in gitter, was a weird bug, and it continues to be. I have the same issue with the latest releases on different projects 😭

**Comment by Enngage** [comment]
I think a new issue like is arose with the latest version that might be related to this.

In admin layout the back button in `md-toolbar` is supposed to be visible when screen is smaller than **gt-sm**, but if the text in toolbar is assigned after the view was initialized (e.g. when title is changed by subscription) the button stays visible. For now I've solved it with 

`tdMediaToggle="gt-sm" [mediaStyles]="{display: 'none'}"`

But its probably not ideal.

**Comment by emoralesb05** [comment]
I still havent been able to replicate it, not even in the quickstart demo 😞 .. maybe im missing something?

**Comment by Enngage** [comment]
What about if you try these steps:

- Go to [https://teradata.github.io/covalent-quickstart/](https://teradata.github.io/covalent-quickstart/)
- Go to _Menu -> Manage users_
- Click '+' button in the bottom right corner
- Click 'CANCEL' button in the user form

After clicking cancel, you should be redirectet back to users page which has the issue. I've been able to reproduce it like this on multiple PC across different browsers so I don't think its related to my environment.

**Comment by emoralesb05** [comment]
Those are the exact same steps i've been doing without any luck 😞 .. 

Tried it in:
- Chrome Version 59.0.3071.115 (64 bit) 
- Firefox 54.0.1 (64-bit)
- Safari 

Is this an intermittent bug? or does it always happen for you?

**Comment by Enngage** [comment]
Thank you for the effort! 

Yeah, this happens consistently. I have exactly the same version of Chrome as you do. See here:

![sidenav2](https://user-images.githubusercontent.com/7137351/28185179-a7246bf2-6816-11e7-8958-a3a030108434.gif)

Kind of strange you can't reproduce it on the same site with the same browser. What else could be different? Is there some 'hidden' loggin on the sample demo site? What about if you try it in an anonymous window?

**Comment by emoralesb05** [comment]
Yeah, gonna keep trying diff screen sizes and stuff like that to see if i can replicate it.

**Comment by Enngage** [comment]
So, I just upgraded to latest version of Angular (4.3.2) and the issue was resolved :-)

**Comment by emoralesb05** [comment]
Ah cool cool! still havent been able to figure out what the problem is haha but atleast that solves it

**Comment by emoralesb05** [comment]
Closing since there hasnt been any issues with this anymore

**Comment by kingkassem** [comment]
the problem still for me with angular 5
more over when open the demo for the quickstart it's there !!!!
